/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2024-08-14 14:03:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	table {\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		border:  1px solid lightseagreen;\r\n");
      out.write("	}\r\n");
      out.write("	thead {\r\n");
      out.write("		background-color: lightseagreen;\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("	tfoot{\r\n");
      out.write("		background-color: lightseagreen;\r\n");
      out.write("	}\r\n");
      out.write("	td{\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		padding: 3px;\r\n");
      out.write("	}\r\n");
      out.write("	th{\r\n");
      out.write("		height: 30px;\r\n");
      out.write("		padding: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	input[type=button], input[type=reset]{\r\n");
      out.write("		background-color: lightseagreen;\r\n");
      out.write("		border: 1px solid white;\r\n");
      out.write("		padding: 5px;\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("	input[type=button]:hover {\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		color: lightseagreen;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" defer>\r\n");
      out.write("	function view_all(){\r\n");
      out.write("		location.href = \"view_all.jsp\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function view_one(f){\r\n");
      out.write("		let regId = /^[0-9a-zA-Z]{8,16}$/;\r\n");
      out.write("		if (!regId.exec(f.id.value)) {\r\n");
      out.write("		    alert(\"대소문자와 소문자를 혼합한 8~16자의 아이디를 입력해 주세요.\");\r\n");
      out.write("		    f.id.value = \"\";\r\n");
      out.write("		    f.id.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("		}\r\n");
      out.write("		f.action = \"view_one.jsp\";\r\n");
      out.write("		f.submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function insert_one(f){\r\n");
      out.write("		let regId = /^[0-9a-zA-Z]{8,16}$/;\r\n");
      out.write("		if (!regId.exec(f.id.value)) {\r\n");
      out.write("		    alert(\"대소문자와 소문자를 혼합한 8~16자의 아이디를 입력해 주세요.\");\r\n");
      out.write("		    f.id.value = \"\";\r\n");
      out.write("		    f.id.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("		}\r\n");
      out.write("		let regPw = /^[0-9a-zA-Z]{8,16}$/;\r\n");
      out.write("		if (!regPw.exec(f.pw.value)) {\r\n");
      out.write("		    alert(\"대소문자와 소문자를 혼합한 8~16자의 비밀번호를 입력해 주세요.\");\r\n");
      out.write("		    f.pw.value = \"\";\r\n");
      out.write("		    f.pw.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("		}\r\n");
      out.write("		let koreanRegName = /^[가-힣]{2,6}$/;\r\n");
      out.write("	    if (!koreanRegName.exec(f.name.value)) {\r\n");
      out.write("		    alert(\"올바른 이름을 입력해 주세요.\");\r\n");
      out.write("		    f.name.value = \"\";\r\n");
      out.write("		    f.name.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("	    }\r\n");
      out.write("	    let regAge = /^[0-9]{1,3}$/;\r\n");
      out.write("	    if (!regAge.exec(f.age.value)) {\r\n");
      out.write("		    alert(\"올바른 나이를 입력해 주세요.\");\r\n");
      out.write("		    f.age.value = \"\";\r\n");
      out.write("		    f.age.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("	    }\r\n");
      out.write("	    let regAddr = /^[가-힣0-9\\s]{5,30}$/;\r\n");
      out.write("	    if (!regAddr.exec(f.addr.value)) {\r\n");
      out.write("		    alert(\"올바른 주소를 5자 이상 입력해 주세요\");\r\n");
      out.write("		    f.addr.value = \"\";\r\n");
      out.write("		    f.addr.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("	    }\r\n");
      out.write("		f.action = \"insert_one.jsp\";\r\n");
      out.write("		f.submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function remove_one(f){\r\n");
      out.write("		let regId = /^[0-9a-zA-Z]{8,16}$/;\r\n");
      out.write("		if (!regId.exec(f.id.value)) {\r\n");
      out.write("		    alert(\"대소문자와 소문자를 혼합한 8~16자의 아이디를 입력해 주세요.\");\r\n");
      out.write("		    f.id.value = \"\";\r\n");
      out.write("		    f.id.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("		}\r\n");
      out.write("		let regPw = /^[0-9a-zA-Z]{8,16}$/;\r\n");
      out.write("		if (!regPw.exec(f.pw.value)) {\r\n");
      out.write("		    alert(\"대소문자와 소문자를 혼합한 8~16자의 비밀번호를 입력해 주세요.\");\r\n");
      out.write("		    f.pw.value = \"\";\r\n");
      out.write("		    f.pw.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("		}\r\n");
      out.write("		f.action = \"remove_one.jsp\";\r\n");
      out.write("		f.submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function update_one(f){\r\n");
      out.write("		let regId = /^[0-9a-zA-Z]{8,16}$/;\r\n");
      out.write("		if (!regId.exec(f.id.value)) {\r\n");
      out.write("		    alert(\"대소문자와 소문자를 혼합한 8~16자의 아이디를 입력해 주세요.\");\r\n");
      out.write("		    f.id.value = \"\";\r\n");
      out.write("		    f.id.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("		}\r\n");
      out.write("		let regPw = /^[0-9a-zA-Z]{8,16}$/;\r\n");
      out.write("		if (!regPw.exec(f.pw.value)) {\r\n");
      out.write("		    alert(\"대소문자와 소문자를 혼합한 8~16자의 비밀번호를 입력해 주세요.\");\r\n");
      out.write("		    f.pw.value = \"\";\r\n");
      out.write("		    f.pw.focus();\r\n");
      out.write("		    return;\r\n");
      out.write("		}\r\n");
      out.write("		f.action = \"update_one.jsp\";\r\n");
      out.write("		f.submit();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form method=\"post\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th colspan=\"2\">회원 정보 관리</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>아이디</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"id\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>비밀번호</td>\r\n");
      out.write("					<td><input type=\"password\" name=\"pw\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>이름</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>나이</td>\r\n");
      out.write("					<td><input type=\"number\" name=\"age\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>주소</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"addr\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tbody>\r\n");
      out.write("			<tfoot>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th colspan=\"2\">\r\n");
      out.write("						<input type=\"button\" value=\"전체보기\" onclick=\"view_all()\">&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"button\" value=\"검색\" onclick=\"view_one(this.form)\">&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"button\" value=\"삽입\" onclick=\"insert_one(this.form)\">&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"button\" value=\"삭제\" onclick=\"remove_one(this.form)\">&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"button\" value=\"수정\" onclick=\"update_one(this.form)\">&nbsp;&nbsp;\r\n");
      out.write("						<input type=\"reset\" value=\"다시 작성\">\r\n");
      out.write("					</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</tfoot>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
